### ISSUE TITLE
Cancellation token for commit

### ISSUE THREAD

**Issue by bakosk** [Kros-sk/Kros.KORM#102]
it would be nice if ITransaction.Commit() method could accept cancelation token and rollback transaction if provided. If it is feasible() :) 

It could be something like this https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbtransaction.commitasync?view=net-6.0&viewFallbackFrom=dotnet-plat-ext-6.0#system-data-common-dbtransaction-commitasync(system-threading-cancellationtoken)

**Comment by Burgyn** [comment]
I'll look into it
