### ISSUE TITLE
Support converters for all properties of specified type

### ISSUE THREAD

**Issue by satano** [Kros-sk/Kros.KORM#21]
Now if I want to use the same converter for several properties, I have to annotate them all. It would be nice to have a converter attribute for table, which will be used for all properties of specified type.

For now, the only useful example I have is, that I want for all string properties to convert `null` values to empty string (because string columns in database are `NOT NULL)`. And to have just one attribute on class is cleaner than to have attributed ever property.

We have to take care about:

- If the property itself has `Converter` attribute it has precedence over attribute on class.
- We need to say somehow that the property does not want to use converter from class (`NoConverterAttribute`?). For example if I have 10 string properties and I want to use converter for all of them except one.

**Comment by Burgyn** [comment]
I suggest that new things are not done through attributes but by fluent definition.

Something like:

```CSharp
public class DatabaseConfiguration: DatabaseConfigurationBase
{
    public override void OnModelCreating(ModelConfigurationBuilder modelBuilder)
    {
        modelBuilder.Entity<Foo>()
            .PropertiesWithType<string>().UseConverter<NullToStringEmptyConverter>()
            .Property(f => f.SpecialProperty).IgnoreConverter();
    }
}
```
