### ISSUE TITLE
Nullable nvarchar/varchar column with null value mapping to string record

### ISSUE THREAD

**Issue by rudolfficek** [Kros-sk/Kros.KORM#80]
## Library name and version
- Kros.KORM 4.1.1

## Description

Mapping null value to record string property is not working. Mapping to class is working as expected.

## Steps To Reproduce
1. Create table with NULLable string column (for example [nvarchar](255))
2. Insert testing data where column value is NULL
3. Create query with KORM and map as record.

you can check my tests to reproduce issue:
[https://github.com/rudolfficek/Korm.Query.Tests/blob/16c61b02ca72d82ae7f3f113a4eacb1eb140f962/Korm.Query.Tests/QuerieTests/BuiltQueryWithNullableShould.cs#L78](url)

## Expected behavior
Null value should be correcly mapped.

## Actual behavior
exception thrown. System.Data.SqlTypes.SqlNullValueException : Data is Null. This method or property cannot be called on Null values.

**Comment by satano** [comment]
I was not able to reproduce this (maybe I did not understand the problem). Add tests for this in #88.
